import { SliderProps } from "@/components/Slider/SliderMotion";

export const certificates: SliderProps[]= [
  {
    title: "Formação em Desenvolvimento Full-Stack",
    description: "Carga horária de 1.500 horas.",
    url: "https://www.credential.net/0a3d484e-967c-491f-9f8e-05192e5608d2#gs.9u4x7j",
    institution: "Trybe",
    date: "17 de Maio, 2024",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/103983801",
    tags: ["Fundamentos do Desenvolvimento Web", "Front-end", "Back-end", "Ciências da Computação", "Soft Skills", "Metodologias Ágeis", "Eletiva C#"],
    stack: "",
    deploy: "",
    repository: "",
  },
  {
    title: "Certificação Eletiva em C#",
    description: "Carga horária de 270 horas.",
    url: "https://www.credential.net/71052745-b3a4-4b92-bd06-730ab3e17c31#gs.9ua0ib",
    institution: "Trybe",
    date: "12 de Maio, 2024",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/103562471",
    tags: ["C#", ".NET Core", "ASP.NET", "xUnit", "SQL Server", "Entity Framework", "Docker", "Azure", "Swagger", "JWT", "Arquitetura de Microsserviços"],
    stack: "",
    deploy: "",
    repository: "",
  },
  {
    title: "Módulo de Ciência da Computação",
    description: "Carga horária de 140 horas.",
    url: "https://www.credential.net/9e1aae72-beb7-4de1-bf41-52f661230d8a#gs.9ua0qa",
    institution: "Trybe",
    date: "27 de Fevereiro, 2024",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/96143718",
    tags: ["Python", "Recursividade", "POO", "Estrutura de Dados", "Complexidade de Algoritmos", "Algoritmos de Ordenação e Busca"],
    stack: "",
    deploy: "",
    repository: "",
  },
  {
    title: " Módulo de Desenvolvimento em Back End",
    description: "Carga horária de 410 horas.",
    url: "https://www.credential.net/dc4fe166-48c3-4e9c-8da7-745d2ad2e144#gs.9ua14h",
    institution: "Trybe",
    date: "23 de Julho, 2024",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/92786586",
    tags: ["TypeScript", "NodeJs", "Express", "MySQL", "Arquitetura em Camadas", "Sequelize", "Docker", "SOLID", "POO", "Deployment", "JWT", "REST", "Mocha", "Chai", "Sinon"],
    stack: "",
    deploy: "",
    repository: "",
  },
  {
    title: "Módulo de Front-End",
    description: "Carga horária de 405 horas.",
    url: "https://www.credential.net/8af7da4e-e234-4dd9-8f58-6f23d9f070f8#gs.9ua182",
    institution: "Trybe",
    date: "19 de Setembro, 2023",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/82367199",
    tags: ["JavaScript", "TypeScript", "React", "Redux", "Context API & Hooks", "Testing Library", "React Router", "Metodologias Ágeis", "Jest", "Bootstrap", "Styled Components"],
    stack: "",
    deploy: "",
    repository: "",
  },
  {
    title: "Módulo de Fundamentos do Desenvolvimento Web",
    description: "Carga horária de 275 horas.",
    url: "https://www.credential.net/dfe79db1-5328-4e25-9b1e-2000d32e345b#gs.9ua19j",
    institution: "Trybe",
    date: "14 de Junho, 2023",
    preview: "https://api.accredible.com/v1/frontend/credential_website_embed_image/certificate/75611329",
    tags: ["JavaScript", "HTML", "CSS", "Git & GitHub", "Unix & Bash", "HOFs", "Testes Unitários", "Lógica de Programação", "Metodologias Ágeis"],
    stack: "",
    deploy: "",
    repository: "",
  },
];

// {
///////PROJECTS ONLY/////////////////////////
//   deploy: "",
//   repository: "",
//   stack: "",
//////CERTIFICATES ONLY//////////////////////
//   url: "",
//   institution: "";
//   date: "";
//////FOR ALL///////////////////////////////
//   title: "",
//   description: "",
//   preview: "",
//   tags: ["", "", "", "", ""],
// },


// {
//   title: "",
//   description: "Carga horária de XX horas.",
//   url: "",
//   institution: "Trybe",
//   date: "",
//   preview: "",
//   tags: [""],
//   stack: "",
//   deploy: "",
//   repository: "",
// },