export const projects = [
  {
    stack: "Backend",
    title: "Trybe Hotel",
    description: "Aplicação web API REST desenvolvida em ASP.NET, com o objetivo de gerenciar uma empresa de hotelaria, com diversas sedes, através de CRUD e armazená-las em um banco de dados.",
    deploy: "",
    repository: "https://github.com/hiagoisoppo/trybe-hotel",
    preview: "https://raw.githubusercontent.com/hiagoisoppo/trybe-hotel/main/public/Preview.png",
    tags: ["C#", "ASP.Net Core", "JwtBearer", "EntityFrameworkCore", "SqlServer", "Swagger", "Docker"],
  },
  {
    stack: "Backend",
    title: "TryBets",
    description: "Uma RestAPI, desenvolvida em ASP.NET com o objetivo de gerenciar uma casa de apostas, através de um CRUD em microsserviços.",
    deploy: "",
    repository: "https://github.com/hiagoisoppo/trybets",
    preview: "https://raw.githubusercontent.com/hiagoisoppo/trybets/main/public/Preview.png",
    tags: ["C#", "ASP.Net Core", "JwtBearer", "EntityFrameworkCore", "SqlServer", "Swagger", "Docker"],
  },
  {
    stack: "Backend",
    title: "API Blog",
    description: "Uma REST API, desenvolvida com o objetivo de gerenciar através de um CRUD as postagens de um blog e armazenalas em um banco de dados, com as seguranças e validações necessarias.",
    deploy: "",
    repository: "https://github.com/hiagoisoppo/api-blog",
    preview: "https://raw.githubusercontent.com/hiagoisoppo/api-blog/hiago-isoppo-blogs-api/public/Preview.png",
    tags: ["JavaScript", "NodeJs", "MySQL", "Sequelize", "Mocha", "JsonWebToken", "Express", "Docker"],
  },
  {
    stack: "Frontend",
    title: "Gourmet Guidance",
    description: "Aplicação web que funciona como um guia gourmet para entusiastas da culinária e da bebida.",
    deploy: "https://gourmet-guidance.vercel.app/",
    repository: "https://github.com/hiagoisoppo/gourmet-guidance",
    preview:"https://raw.githubusercontent.com/hiagoisoppo/gourmet-guidance/main-group-5/public/Preview.png",
    tags: ["TypeScript", "Docker", "ReactJs", "Redux", "Bootstrap", "Cypress", "Mocha", "Sass"],
  },
  {
    stack: "Fullstack",
    title: "Trybe Futebol Clube",
    description: "Aplicação web full stack, desenvolvida em monorepo com o objetivo de registrar e organizar a pontuação em um campeonato de futebol fictício.",
    deploy: "",
    repository: "https://github.com/hiagoisoppo/trybe-futebol-club",
    preview: "https://raw.githubusercontent.com/hiagoisoppo/trybe-futebol-club/hiago-isoppo-sd-032-project-trybe-futebol-clube/public/Preview.png",
    tags: ["TypeScript", "Docker", "ReactJs", "Puppeteer", "Axios", "Mocha", "TsNode", "Express", "Sequelize", "MySQL"],
  },
  {
    stack: "Frontend",
    title: "HIT News",
    description: "Aplicação web desenvolvida com o objetivo de distribuir e organizar as notícias mais recentes, disponibilizadas através da API do IBGE.",
    deploy: "https://hitnews.vercel.app/",
    repository: "https://github.com/hiagoisoppo/hit-news",
    preview: "https://raw.githubusercontent.com/hiagoisoppo/hit-news/main/public/Preview.png",
    tags: ["TypeScript", "ReactJs", "TailwindCSS", "PostCss", "ReactTestingLibrary", "Vitest"],
  },
  {
    stack: "Frontend",
    title: "Portfólio",
    description: "Portfólio profissional, desenvolvido com o objetivo de apresentar meus projetos e habilidades.",
    deploy: "https://hiagoisoppo.dev/",
    repository: "https://github.com/hiagoisoppo/portfolio",
    preview: "",
    tags: ["NextJs", "ReactJs", "TypeScript", "CSS Modules", "Framer Motion"],
  },
];
